# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ZedStreamer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ZedStreamer.proto',
  package='zedstreamer',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11ZedStreamer.proto\x12\x0bzedstreamer\":\n\x05Image\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x12\n\nimage_data\x18\x03 \x01(\x0c\"\x17\n\x08Received\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\x32\x83\x01\n\x0bZedStreamer\x12\x38\n\tSendImage\x12\x12.zedstreamer.Image\x1a\x15.zedstreamer.Received\"\x00\x12:\n\tSendVideo\x12\x12.zedstreamer.Image\x1a\x15.zedstreamer.Received\"\x00(\x01\x62\x06proto3'
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='zedstreamer.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='zedstreamer.Image.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='zedstreamer.Image.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_data', full_name='zedstreamer.Image.image_data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=92,
)


_RECEIVED = _descriptor.Descriptor(
  name='Received',
  full_name='zedstreamer.Received',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ack', full_name='zedstreamer.Received.ack', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['Received'] = _RECEIVED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'ZedStreamer_pb2'
  # @@protoc_insertion_point(class_scope:zedstreamer.Image)
  })
_sym_db.RegisterMessage(Image)

Received = _reflection.GeneratedProtocolMessageType('Received', (_message.Message,), {
  'DESCRIPTOR' : _RECEIVED,
  '__module__' : 'ZedStreamer_pb2'
  # @@protoc_insertion_point(class_scope:zedstreamer.Received)
  })
_sym_db.RegisterMessage(Received)



_ZEDSTREAMER = _descriptor.ServiceDescriptor(
  name='ZedStreamer',
  full_name='zedstreamer.ZedStreamer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=120,
  serialized_end=251,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendImage',
    full_name='zedstreamer.ZedStreamer.SendImage',
    index=0,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_RECEIVED,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendVideo',
    full_name='zedstreamer.ZedStreamer.SendVideo',
    index=1,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_RECEIVED,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ZEDSTREAMER)

DESCRIPTOR.services_by_name['ZedStreamer'] = _ZEDSTREAMER

# @@protoc_insertion_point(module_scope)
